sonar.projectKey=blog
sonar.sources=.
sonar.sca.exclusions="**/migrations/**,**/.venv/**,**/.uv-cache/**,**/.ruff_cache/**,**/sentence_transformers_models/**,**/media/**,**/staticfiles/**"
sonar.python.version=3.14
