# Generated by Django 6.0.3 on 2026-04-12 07:20

import django.db.models.deletion
from django.db import migrations, models

import media_service.models.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.CharField(max_length=64, unique=True)),
                (
                    "file",
                    models.ImageField(
                        upload_to=media_service.models.image.image_raw_upload_path
                    ),
                ),
                (
                    "avif_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=media_service.models.image.image_avif_upload_path,
                    ),
                ),
                (
                    "webp_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=media_service.models.image.image_webp_upload_path,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=media_service.models.image.image_thumbnail_upload_path,
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=50)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["checksum"], name="media_servi_checksu_efb50b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("uploader_id", models.PositiveIntegerField()),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "uploader_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="media_service.imageresource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
