apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog

resources:
- ../../base
- ingress.yaml
- cluster-issuer.yaml
- middleware-whitelist.yaml

# In prod, images are managed by Woodpecker CI & Argo CD
images:
- name: blog-app
  newName: registry.gsgfs.sh/blog-app
  newTag: 5e3c41c9af2927a5d4ef3d654350b3de213f789d
- name: blog-backup
  newName: registry.gsgfs.sh/blog-backup
  newTag: 5e3c41c9af2927a5d4ef3d654350b3de213f789d
