apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog

resources:
- ../../base
- ingress.yaml
- cluster-issuer.yaml
- middleware-whitelist.yaml

# In prod, images are managed by Woodpecker CI & Argo CD
images:
- name: blog-backup
  newName: registry.gsgfs.sh/blog-backup
  newTag: bb0e13b5d029cc5a3a19dde4a41d80335d029558
- name: blog-celery-beat
  newName: registry.gsgfs.sh/blog-celery-beat
  newTag: bb0e13b5d029cc5a3a19dde4a41d80335d029558
- name: blog-celery-worker
  newName: registry.gsgfs.sh/blog-celery-worker
  newTag: bb0e13b5d029cc5a3a19dde4a41d80335d029558
- name: blog-django
  newName: registry.gsgfs.sh/blog-django
  newTag: bb0e13b5d029cc5a3a19dde4a41d80335d029558
- name: blog-model-downloader
  newName: registry.gsgfs.sh/blog-model-downloader
  newTag: bb0e13b5d029cc5a3a19dde4a41d80335d029558
