# Generated by Django 5.1.5 on 2025-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_options_post_meta_description_post_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True, help_text='文章封面图片(URL)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.URLField(blank=True, help_text='文章顶部大图(URL)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='url 地址', max_length=100, unique=True),
        ),
    ]
