# Generated by Django 5.1.5 on 2025-01-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_created_at_alter_post_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
