# Generated by Django 5.1.5 on 2025-01-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='provider',
            field=models.CharField(choices=[('github', 'github'), ('google', 'google'), ('myself', 'myself')], default='myself', max_length=10),
        ),
    ]
