# Generated by Django 5.1.5 on 2025-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_guest_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='unique_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='provider',
            field=models.CharField(choices=[('github', 'github'), ('google', 'google'), ('myself', 'myself'), ('osu', 'osu')], default='myself', max_length=10),
        ),
    ]
