# Generated by Django 5.1.5 on 2025-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='guest',
        ),
        migrations.AlterField(
            model_name='guest',
            name='unique_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
