# Generated by Django 5.1.5 on 2025-02-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_author_comment_guest_alter_guest_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_deleted',
        ),
    ]
