# Generated by Django 5.1.6 on 2025-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_comment_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='provider_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
