# Generated by Django 5.1.6 on 2025-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_guest_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='avatar',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
