# Generated by Django 5.1.6 on 2025-03-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_comment_browser_comment_device_comment_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='device',
        ),
        migrations.AddField(
            model_name='comment',
            name='browser_version',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='platform',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='browser',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='os',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_agent',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
    ]
