# Generated by Django 5.1.6 on 2025-03-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_comment_device_comment_browser_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='os',
            new_name='OS',
        ),
    ]
