# Generated by Django 5.1.7 on 2025-03-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_os_comment_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, help_text='文章封面图片(URL)', max_length=500, null=True)),
                ('header_image', models.URLField(blank=True, help_text='文章顶部大图(URL)', max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, help_text='url 地址', max_length=100, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO描述, 留空将自动生成', max_length=160)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('order', models.IntegerField(default=0, help_text='是否覆盖默认的优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='api.author')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='api.category')),
                ('tags', models.ManyToManyField(blank=True, default=None, related_name='pages', to='api.tag')),
            ],
            options={
                'ordering': ['-order', '-created_at'],
            },
        ),
    ]
