# Generated by Django 5.1.7 on 2025-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vndb_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('character_score', models.FloatField()),
                ('story_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('review', models.TextField()),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
