# Generated by Django 5.1.7 on 2025-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_gal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gal',
            name='character_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gal',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gal',
            name='story_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
