# Generated by Django 5.1.7 on 2025-03-27 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_gal_character_score_alter_gal_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gal',
            name='name',
        ),
        migrations.AddField(
            model_name='gal',
            name='comprehensive_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gal',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gal',
            name='title_cn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gal',
            name='vndb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gal',
            name='vndb_id',
            field=models.IntegerField(unique=True),
        ),
    ]
