# Generated by Django 5.2.1 on 2025-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_guest_created_at_guest_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.CharField(blank=True, help_text='文章关键词，用逗号分隔', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, help_text='文章关键词，用逗号分隔', max_length=200),
        ),
    ]
