# Generated by Django 5.2.1 on 2025-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_author_created_at_author_update_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='as_author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
