# Generated by Django 5.2.4 on 2025-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(default=1, help_text='在MyAnimeList中的ID, 必填'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gal',
            name='vndb_id',
            field=models.CharField(help_text='在VNDB中的ID, 必填', max_length=10, unique=True),
        ),
    ]
