# Generated by Django 5.2.4 on 2025-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_anime_mal_id_alter_gal_vndb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
