# Generated by Django 5.2.4 on 2025-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_anime_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='alias',
        ),
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(blank=True, null=True),
        ),
    ]
