# Generated by Django 5.2.4 on 2025-07-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_anime_alias_anime_score_anime_synopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.guest'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
        migrations.AlterField(
            model_name='gal',
            name='cover_image',
            field=models.URLField(blank=True, help_text='(暂时没用)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gal',
            name='summary',
            field=models.CharField(blank=True, help_text='显示在外面, 类似于备注', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='文章正文, 必填'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, help_text='(暂时没用)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.URLField(blank=True, help_text='文章og显示图片(URL)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO描述', max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0, help_text='是否覆盖默认的优先级, 数值越大越靠前'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='url 地址 (暂时没用)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='posts', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='(暂时没用)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
