# Generated by Django 5.2.4 on 2025-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_category_name_alter_comment_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gal',
            name='review_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
