# Generated by Django 5.2.4 on 2025-07-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_gal_review_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='gal',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
