# Generated by Django 5.2.6 on 2025-09-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_rename_update_at_anime_updated_at_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]
