# Generated by Django 5.2.6 on 2025-09-13 14:18

from django.db import migrations


def create_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def drop_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP EXTENSION IF EXISTS vector;")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_rename_update_at_anime_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(create_extension, drop_extension),
    ]
