# Generated by Django 5.2.6 on 2025-09-12 05:41

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_update_at_anime_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
