# Generated by Django 5.2.6 on 2025-09-13 14:23

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_enable_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, help_text='自动生成', null=True),
        ),
    ]
