# Generated by Django 5.2.6 on 2025-09-16 12:12

from django.db import migrations, models


def set_content_update_at_from_update_at(apps, schema_editor):
    Post = apps.get_model("api", "Post")
    for post in Post.objects.all():
        post.content_update_at = post.updated_at
        post.save()


def reverse_set_content_update_at(apps, schema_editor):
    Post = apps.get_model("api", "Post")
    for post in Post.objects.all():
        post.content_update_at = None
        post.save()


# Read doc: https://docs.djangoproject.com/zh-hans/5.2/topics/migrations/#adding-migrations-to-apps
class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_post_embedding_alter_post_content_html"),
    ]

    operations = [
        # 1. allow empty
        migrations.AddField(
            model_name="post",
            name="content_update_at",
            field=models.DateTimeField(
                null=True, blank=True, help_text="文章正文最后更新时间"
            ),
        ),
        # 2. fill data
        migrations.RunPython(
            set_content_update_at_from_update_at,
            reverse_set_content_update_at,
        ),
        # 3. alter to not allow empty
        migrations.AlterField(
            model_name='post',
            name='content_update_at',
            field=models.DateTimeField(
                null=False, blank=True, help_text="文章正文最后更新时间"
            ),
        )
    ]
