# Generated by Django 5.2.11 on 2026-02-21 16:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_post_content_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pg_gin_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tokenized_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["pg_gin_search_vector"], name="api_post_pg_gin__ce08df_gin"
            ),
        ),
    ]
