# Generated by Django 5.2.11 on 2026-02-24 10:18

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_post_pg_gin_search_vector_post_tokenized_content_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="api_post_embedding_cosine_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
