# Generated by Django 6.0.3 on 2026-03-27 15:29

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_imageresource_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                ("chunk_index", models.IntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="api_post_embedding_cosine_idx",
        ),
        migrations.AddField(
            model_name="postchunk",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="api.post",
            ),
        ),
        migrations.RemoveField(
            model_name="post",
            name="embedding",
        ),
        migrations.AddIndex(
            model_name="postchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=256,
                fields=["embedding"],
                m=32,
                name="post_chunk_embedding_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
