# Generated by Django 6.0.3 on 2026-04-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_remove_post_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="image",
            name="uploaded_by",
        ),
        migrations.RemoveIndex(
            model_name="imageresource",
            name="api_imagere_checksu_b100a3_idx",
        ),
        migrations.DeleteModel(
            name="ImageResource",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
