depends_on:
  - test

# specify an agent run the pipline which has this label
labels:
  type: builder
  # set agent env to use the label:
  #  WOODPECKER_AGENT_LABELS: type=builder

when:
  - event: [ push, pull_request, manual ]
    branch:
      - main
      - woodpecker-test

steps:
  - name: build
    image: docker.io/library/archlinux:latest
    when:
      event: [ push, manual ]
    # SECURITY WARNING: privileged is enable, makesure you trust all for the code
    # privileged: true
    environment:
      REGISTRY_DOMAIN:
        from_secret: REGISTRY_DOMAIN
      REGISTRY_IP:
        from_secret: REGISTRY_IP
      REGISTRY_USERNAME:
        from_secret: REGISTRY_USERNAME
      HUGGINGFACE_HUB_TOKEN:
        from_secret: HUGGINGFACE_HUB_TOKEN
      REGISTRY_PASSWORD:
        from_secret: REGISTRY_PASSWORD
      STORAGE_DRIVERL: overlayfs
    commands:
      #- pacman -Sy --noconfirm
      #- pacman -S podman fuse-overlayfs --noconfirm  # overlayfs storage driver in user space
      # bypass CF CDN
      #- echo "$REGISTRY_IP $REGISTRY_DOMAIN" >> /etc/hosts
      #- ./scripts/build-and-push.sh
      - echo "ciallo!"
