depends_on:
  - test

# specify an agent run the pipline which has this label
labels:
  type: builder
  # set agent env to use the label:
  #  WOODPECKER_AGENT_LABELS: type=builder

when:
  - event: [ push, manual ]
    branch:
      - main
      - woodpecker-test

steps:
  - name: build
    image: docker.io/library/archlinux:latest
    # SECURITY WARNING: privileged is enable, makesure you trust all for the code
    privileged: true
    environment:
      REGISTRY_DOMAIN:
        from_secret: REGISTRY_DOMAIN
      REGISTRY_IP:
        from_secret: REGISTRY_IP
      REGISTRY_CA_CERT:
        from_secret: REGISTRY_CA_CERT
      REGISTRY_CLIENT_CERT:
        from_secret: REGISTRY_CLIENT_CERT
      REGISTRY_CLIENT_KEY:
        from_secret: REGISTRY_CLIENT_KEY
      #REGISTRY_USERNAME:
      #  from_secret: REGISTRY_USERNAME
      #REGISTRY_PASSWORD:
      #  from_secret: REGISTRY_PASSWORD
      HUGGINGFACE_HUB_TOKEN:
        from_secret: HUGGINGFACE_HUB_TOKEN
      STORAGE_DRIVERL: overlayfs
    commands:
      - pacman -Sy podman fuse-overlayfs --noconfirm  # overlayfs storage driver in user space
      # bypass CF CDN
      - echo "$REGISTRY_IP $REGISTRY_DOMAIN" >> /etc/hosts
      - ./scripts/build-and-push.sh
