when:
  - event: [ push, pull_request, manual ]
    branch: [ main ]

steps:
  - name: set-inotify-limit
    image: docker.io/library/archlinux:latest
    privileged: true
    commands:
      - sysctl -w fs.inotify.max_user_watches=524288

  - name: scan
    depends_on:
      - set-inotify-limit
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_HOST_URL: https://sonarqube.gsgfs.sh
