name: Docker Image CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker buildx build -t django .

      - name: Export Docker image
        run: |
          mkdir -p ./artifacts
          cd ./artifacts
          docker save django:latest | zstd -c -T0 --ultra -20 > 'django.tar.zst'
          sha256sum django.tar.zst > django.tar.zst.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./artifacts
          retention-days: 7
