# mirror GitOps

name: Mirror to Codeberg

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  codeberg-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@codeberg.org:GSGFs7/GSGFs-blog-backend.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
